---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: blue
  namespace: flux-system
spec:
  chart:
    spec:
      chart: charts/generic
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: GitRepository
        name: flux-system
  interval: 1m0s
  releaseName: blue
  targetNamespace: default
  values:
    image:
      repository: jpetazzo/color
      tag: latest
