apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: purple
    le-yaml: c-est-la-vie
  name: purple
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purple
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: purple
    spec:
      containers:
      - image: jpetazzo/color
        name: color
